import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import type { Invoice, InvoiceItem, Customer, Product, Company } from '@/db/database';

// Export Invoice to PDF
export async function exportInvoiceToPDF(
  invoice: Invoice,
  items: InvoiceItem[],
  company: Company | null,
  customer: Customer | null
): Promise<Blob> {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(26, 26, 26);
  doc.text('INVOICE', 20, 30);
  
  // Company Info
  doc.setFontSize(10);
  doc.setTextColor(92, 92, 92);
  if (company) {
    doc.text(company.name, 20, 45);
    doc.text(company.address || '', 20, 50);
    doc.text(`Phone: ${company.phone}`, 20, 55);
    doc.text(`Email: ${company.email}`, 20, 60);
  }
  
  // Invoice Details
  doc.setFontSize(11);
  doc.setTextColor(26, 26, 26);
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 140, 45);
  doc.text(`Date: ${new Date(invoice.date).toLocaleDateString()}`, 140, 52);
  doc.text(`Status: ${invoice.status.toUpperCase()}`, 140, 59);
  if (invoice.dueDate) {
    doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 140, 66);
  }
  
  // Customer Info
  doc.setFontSize(12);
  doc.setTextColor(26, 26, 26);
  doc.text('Bill To:', 20, 80);
  doc.setFontSize(10);
  doc.setTextColor(92, 92, 92);
  if (customer) {
    doc.text(customer.name, 20, 88);
    doc.text(customer.address || '', 20, 94);
    doc.text(`Phone: ${customer.phone}`, 20, 100);
    doc.text(`Email: ${customer.email}`, 20, 106);
  }
  
  // Items Table
  const tableData = items.map(item => [
    item.productName,
    item.quantity.toString(),
    `$${item.unitPrice.toFixed(2)}`,
    `$${item.total.toFixed(2)}`,
  ]);
  
  (doc as any).autoTable({
    startY: 120,
    head: [['Product', 'Quantity', 'Unit Price', 'Total']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [26, 26, 26],
      textColor: [255, 255, 255],
    },
    styles: {
      fontSize: 10,
    },
  });
  
  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(10);
  doc.setTextColor(92, 92, 92);
  doc.text(`Subtotal: $${invoice.subtotal.toFixed(2)}`, 140, finalY);
  doc.text(`Tax: $${invoice.tax.toFixed(2)}`, 140, finalY + 7);
  doc.text(`Discount: $${invoice.discount.toFixed(2)}`, 140, finalY + 14);
  
  doc.setFontSize(12);
  doc.setTextColor(26, 26, 26);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total: $${invoice.total.toFixed(2)}`, 140, finalY + 25);
  doc.text(`Paid: $${invoice.paid.toFixed(2)}`, 140, finalY + 32);
  doc.text(`Balance: $${(invoice.total - invoice.paid).toFixed(2)}`, 140, finalY + 39);
  
  // Notes
  if (invoice.notes) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(92, 92, 92);
    doc.text('Notes:', 20, finalY + 55);
    doc.text(invoice.notes, 20, finalY + 62);
  }
  
  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Thank you for your business!', 105, 280, { align: 'center' });
  doc.text('Generated by Choice Inventory System - Developed by Prashanth KV, Choice16 Studio', 105, 285, { align: 'center' });
  
  return doc.output('blob');
}

// Export Invoice to Excel
export async function exportInvoiceToExcel(
  invoice: Invoice,
  items: InvoiceItem[],
  company: Company | null,
  customer: Customer | null
): Promise<Blob> {
  const wb = XLSX.utils.book_new();
  
  // Invoice Info Sheet
  const infoData = [
    ['INVOICE'],
    [],
    ['Invoice Number:', invoice.invoiceNumber],
    ['Date:', new Date(invoice.date).toLocaleDateString()],
    ['Status:', invoice.status],
    ['Due Date:', invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : 'N/A'],
    [],
    ['COMPANY'],
    ['Name:', company?.name || ''],
    ['Address:', company?.address || ''],
    ['Phone:', company?.phone || ''],
    ['Email:', company?.email || ''],
    [],
    ['CUSTOMER'],
    ['Name:', customer?.name || ''],
    ['Address:', customer?.address || ''],
    ['Phone:', customer?.phone || ''],
    ['Email:', customer?.email || ''],
    [],
    ['ITEMS'],
    ['Product', 'Quantity', 'Unit Price', 'Total'],
    ...items.map(item => [
      item.productName,
      item.quantity,
      item.unitPrice,
      item.total,
    ]),
    [],
    ['SUMMARY'],
    ['Subtotal:', invoice.subtotal],
    ['Tax:', invoice.tax],
    ['Discount:', invoice.discount],
    ['Total:', invoice.total],
    ['Paid:', invoice.paid],
    ['Balance:', invoice.total - invoice.paid],
  ];
  
  if (invoice.notes) {
    infoData.push([], ['Notes:', invoice.notes]);
  }
  
  const ws = XLSX.utils.aoa_to_sheet(infoData);
  XLSX.utils.book_append_sheet(wb, ws, 'Invoice');
  
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

// Export Invoice to Word (simplified HTML-based approach)
export async function exportInvoiceToWord(
  invoice: Invoice,
  items: InvoiceItem[],
  company: Company | null,
  customer: Customer | null
): Promise<Blob> {
  const html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>Invoice</title></head>
    <body>
      <h1>INVOICE</h1>
      <p><strong>Invoice Number:</strong> ${invoice.invoiceNumber}</p>
      <p><strong>Date:</strong> ${new Date(invoice.date).toLocaleDateString()}</p>
      <p><strong>Status:</strong> ${invoice.status}</p>
      <hr/>
      <h2>Company</h2>
      <p>${company?.name || ''}</p>
      <p>${company?.address || ''}</p>
      <p>Phone: ${company?.phone || ''}</p>
      <p>Email: ${company?.email || ''}</p>
      <hr/>
      <h2>Customer</h2>
      <p>${customer?.name || ''}</p>
      <p>${customer?.address || ''}</p>
      <p>Phone: ${customer?.phone || ''}</p>
      <p>Email: ${customer?.email || ''}</p>
      <hr/>
      <h2>Items</h2>
      <table border="1" cellpadding="5" cellspacing="0">
        <tr><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Total</th></tr>
        ${items.map(item => `
          <tr>
            <td>${item.productName}</td>
            <td>${item.quantity}</td>
            <td>$${item.unitPrice.toFixed(2)}</td>
            <td>$${item.total.toFixed(2)}</td>
          </tr>
        `).join('')}
      </table>
      <hr/>
      <h2>Summary</h2>
      <p><strong>Subtotal:</strong> $${invoice.subtotal.toFixed(2)}</p>
      <p><strong>Tax:</strong> $${invoice.tax.toFixed(2)}</p>
      <p><strong>Discount:</strong> $${invoice.discount.toFixed(2)}</p>
      <p><strong>Total:</strong> $${invoice.total.toFixed(2)}</p>
      <p><strong>Paid:</strong> $${invoice.paid.toFixed(2)}</p>
      <p><strong>Balance:</strong> $${(invoice.total - invoice.paid).toFixed(2)}</p>
      ${invoice.notes ? `<hr/><p><strong>Notes:</strong> ${invoice.notes}</p>` : ''}
      <hr/>
      <p><em>Thank you for your business!</em></p>
      <p><small>Generated by Choice Inventory System - Developed by Prashanth KV, Choice16 Studio</small></p>
    </body>
    </html>
  `;
  
  return new Blob([html], { type: 'application/msword' });
}

// Export Products to Excel
export async function exportProductsToExcel(products: Product[]): Promise<Blob> {
  const wb = XLSX.utils.book_new();
  
  const data = products.map(p => ({
    SKU: p.sku,
    Name: p.name,
    Description: p.description,
    Category: p.category,
    'Cost Price': p.costPrice,
    'Selling Price': p.sellingPrice,
    Quantity: p.quantity,
    'Min Stock': p.minStock,
    Location: p.location,
    Supplier: p.supplier,
  }));
  
  const ws = XLSX.utils.json_to_sheet(data);
  XLSX.utils.book_append_sheet(wb, ws, 'Products');
  
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

// Export Customers to Excel
export async function exportCustomersToExcel(customers: Customer[]): Promise<Blob> {
  const wb = XLSX.utils.book_new();
  
  const data = customers.map(c => ({
    Name: c.name,
    Email: c.email,
    Phone: c.phone,
    Address: c.address,
    Referral: c.referral,
    'Total Purchases': c.totalPurchases,
    'Total Amount': c.totalAmount,
  }));
  
  const ws = XLSX.utils.json_to_sheet(data);
  XLSX.utils.book_append_sheet(wb, ws, 'Customers');
  
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

// Download blob as file
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
